-- Create sessions for the 29 remaining speakers without sessions

-- Brand & Experience (4 speakers)
INSERT INTO ConfSession (id, conferenceId, title, description, speakerId, room, startsAt, endsAt, track, type, createdAt) VALUES
('ses-g01', 'conf-2025', 'Building Brand Communities That Drive Organic Growth', 'Join Grace Obi for an exploration of community commerce and how to turn customers into co-creators and brand advocates.', 'spk-29', 'Hall A', 1807137000000, 1807139700000, 'Customer Experience', 'TALK', datetime('now')),
('ses-g02', 'conf-2025', 'AR Try-On & Virtual Commerce: Immersive Beauty Experiences', 'Join Leila Ahmadi as she shares how AR technology has increased online beauty sales by 40% through virtual try-on experiences.', 'spk-31', 'Workshop Room A', 1807207200000, 1807209900000, 'Customer Experience', 'WORKSHOP', datetime('now')),
('ses-g03', 'conf-2025', 'Content Commerce: Shoppable Media That Blurs Retail & Entertainment', 'Join Mia Chen as she reveals strategies for building shoppable content that blurs the line between media and retail.', 'spk-37', 'Hall B', 1807217100000, 1807219800000, 'Marketing', 'TALK', datetime('now')),
('ses-g04', 'conf-2025', 'UGC & Social Proof: Leveraging Reviews to Boost Conversions 30%+', 'Join Olivia Thompson as she shares proven strategies for leveraging social proof to dramatically increase conversion rates.', 'spk-13', 'Hall A', 1807131600000, 1807134300000, 'Retention & Subscriptions', 'TALK', datetime('now'));

-- Commerce & Platforms (2 speakers)
INSERT INTO ConfSession (id, conferenceId, title, description, speakerId, room, startsAt, endsAt, track, type, createdAt) VALUES
('ses-g05', 'conf-2025', 'API-First Commerce: Building Flexible Storefronts with Maximum Control', 'Join Adrian Pope as he shares how API-first commerce enables brands to create custom storefronts with maximum flexibility.', 'spk-68', 'Main Stage', 1807207200000, 1807209900000, 'Technology', 'TALK', datetime('now')),
('ses-g06', 'conf-2025', 'Multi-Vendor Marketplace Architecture: From Startup to $100M+ GMV', 'Join Nathan Brooks as he reveals the operational playbook for scaling multi-vendor marketplace platforms.', 'spk-32', 'Hall B', 1807204500000, 1807207200000, 'Enterprise & B2B', 'TALK', datetime('now'));

-- ERP (5 speakers)
INSERT INTO ConfSession (id, conferenceId, title, description, speakerId, room, startsAt, endsAt, track, type, createdAt) VALUES
('ses-g07', 'conf-2025', 'Retail Analytics Dashboards: Real-Time Visibility for Merchants', 'Join Ben Gallagher as he demonstrates how to build real-time analytics dashboards that give merchants full visibility into sales and inventory.', 'spk-70', 'Workshop Room B', 1807207200000, 1807209900000, 'Data & Analytics', 'TALK', datetime('now')),
('ses-g08', 'conf-2025', 'B2B Commerce Digitization: From Catalogs to Self-Service Portals', 'Join Ingrid Larsson as she shares strategies for helping wholesale brands digitize ordering and expand into DTC.', 'spk-43', 'Hall A', 1807217100000, 1807219800000, 'Enterprise & B2B', 'WORKSHOP', datetime('now')),
('ses-g09', 'conf-2025', 'Demand Forecasting & Inventory Planning with ML', 'Join Kevin Wu as he reveals how demand forecasting models help brands eliminate stockouts and overstock situations.', 'spk-56', 'Workshop Room A', 1807134300000, 1807137000000, 'Data & Analytics', 'TALK', datetime('now')),
('ses-g10', 'conf-2025', 'Retail Analytics: Using Data to Predict Trends & Reduce Markdowns', 'Join Patrick O''Sullivan as he shares how data analytics can predict trends, optimize inventory, and reduce markdowns.', 'spk-30', 'Room C', 1807220700000, 1807223400000, 'Data & Analytics', 'TALK', datetime('now')),
('ses-g11', 'conf-2025', 'Localization at Scale: Language, Currency & Cultural Adaptation', 'Join Rosa Fernandez as she reveals how global brands can adapt storefronts for language, culture, and currency differences.', 'spk-61', 'Hall B', 1807118100000, 1807120800000, 'International & Marketplace', 'TALK', datetime('now'));

-- Logistics & Fulfillment (7 speakers)
INSERT INTO ConfSession (id, conferenceId, title, description, speakerId, room, startsAt, endsAt, track, type, createdAt) VALUES
('ses-g12', 'conf-2025', 'Warehouse Automation: Deploying Robotics & AI in Fulfillment Centers', 'Join Andre Williams as he shares how robotics and AI are transforming fulfillment center efficiency.', 'spk-36', 'Workshop Room B', 1807137000000, 1807139700000, 'Operations & Fulfillment', 'WORKSHOP', datetime('now')),
('ses-g13', 'conf-2025', 'Omnichannel Fulfillment: BOPIS, Ship-from-Store & Same-Day Delivery', 'Join Chiara Bianchi as she reveals strategies for implementing omnichannel fulfillment that delights customers.', 'spk-71', 'Hall A', 1807207200000, 1807209900000, 'Operations & Fulfillment', 'TALK', datetime('now')),
('ses-g14', 'conf-2025', 'Real-Time Shipment Tracking: Transparency That Builds Brand Trust', 'Join Nadia Petrova as she shares how shipment tracking and transparency can build lasting customer trust.', 'spk-20', 'Room C', 1807128000000, 1807130700000, 'Customer Experience', 'TALK', datetime('now')),
('ses-g15', 'conf-2025', 'Warehouse Robotics: Autonomous Systems That Triple Throughput', 'Join Omar Bakari as he demonstrates how autonomous robotics systems can triple pick-and-pack throughput.', 'spk-66', 'Workshop Room A', 1807217100000, 1807219800000, 'Operations & Fulfillment', 'TALK', datetime('now')),
('ses-g16', 'conf-2025', 'WMS Optimization: Pick, Pack & Ship for High-Volume Brands', 'Join Priyanka Sharma as she shares warehouse management system strategies for high-volume operations.', 'spk-49', 'Hall B', 1807134300000, 1807137000000, 'Operations & Fulfillment', 'WORKSHOP', datetime('now')),
('ses-g17', 'conf-2025', 'Returns as Growth: Turning a Cost Center into Customer Loyalty', 'Join Ryan Cooper as he reveals how to turn returns from a cost center into a growth engine for Shopify Plus brands.', 'spk-8', 'Main Stage', 1807120800000, 1807123500000, 'Customer Experience', 'TALK', datetime('now')),
('ses-g18', 'conf-2025', 'Post-Purchase Experience Design: Turning Shipping Into Brand Moments', 'Join Sophie Dubois as she shares how to transform shipping anxiety into brand loyalty moments through thoughtful design.', 'spk-15', 'Hall A', 1807220700000, 1807223400000, 'Customer Experience', 'TALK', datetime('now'));

-- Marketing & Growth (1 speaker)
INSERT INTO ConfSession (id, conferenceId, title, description, speakerId, room, startsAt, endsAt, track, type, createdAt) VALUES
('ses-g19', 'conf-2025', 'Retail Media Networks: Monetizing First-Party Data Through On-Site Ads', 'Join Sean Murphy as he reveals how brands can monetize first-party data through on-site advertising and retail media networks.', 'spk-60', 'Room C', 1807204500000, 1807207200000, 'Marketing', 'TALK', datetime('now'));

-- Payments & Checkout (4 speakers)
INSERT INTO ConfSession (id, conferenceId, title, description, speakerId, room, startsAt, endsAt, track, type, createdAt) VALUES
('ses-g20', 'conf-2025', 'Subscription Retention: Using Behavioral Data to Reduce Churn', 'Join Chloe Martin as she shares strategies for using behavioral data to reduce churn and increase customer lifetime value.', 'spk-53', 'Workshop Room B', 1807220700000, 1807223400000, 'Retention & Subscriptions', 'TALK', datetime('now')),
('ses-g21', 'conf-2025', 'Cross-Border Payments: Simplifying International Transactions', 'Join Ling Wei as she reveals how to simplify international payment transactions for global commerce brands.', 'spk-63', 'Hall B', 1807207200000, 1807209900000, 'International & Marketplace', 'TALK', datetime('now')),
('ses-g22', 'conf-2025', 'Mobile Commerce Architecture: Building Apps That Drive 60%+ Revenue', 'Join Oscar Hernandez as he shares how to build mobile commerce apps that drive the majority of brand revenue.', 'spk-38', 'Main Stage', 1807217100000, 1807219800000, 'Technology', 'TALK', datetime('now')),
('ses-g23', 'conf-2025', 'Checkout Optimization: Recovering Millions in Abandoned Cart Revenue', 'Join Tamara Novak as she reveals checkout optimization strategies that recover millions in abandoned cart revenue.', 'spk-57', 'Workshop Room A', 1807120800000, 1807123500000, 'Payments & Checkout', 'WORKSHOP', datetime('now'));

-- Security & Infrastructure (6 speakers)
INSERT INTO ConfSession (id, conferenceId, title, description, speakerId, room, startsAt, endsAt, track, type, createdAt) VALUES
('ses-g24', 'conf-2025', 'Commerce Security: Defending Against Account Takeover & Bot Attacks', 'Join Derek Huang as he shares strategies for protecting brands from account takeover, bot attacks, and payment fraud.', 'spk-72', 'Room C', 1807137000000, 1807139700000, 'Security', 'TALK', datetime('now')),
('ses-g25', 'conf-2025', 'Sustainable Commerce: Building Eco-Friendly Digital Supply Chains', 'Join Emma Johansson as she shares how to build transparent, eco-friendly supply chains for sustainable commerce.', 'spk-35', 'Hall B', 1807128000000, 1807130700000, 'Operations & Fulfillment', 'TALK', datetime('now')),
('ses-g26', 'conf-2025', 'Visual Commerce: 3D & Video Shopping Experiences That Convert', 'Join Isabella Moretti as she demonstrates how immersive 3D and video shopping experiences drive higher engagement.', 'spk-55', 'Workshop Room B', 1807204500000, 1807207200000, 'Technology', 'TALK', datetime('now')),
('ses-g27', 'conf-2025', 'Performance Engineering: Achieving Sub-Second Page Loads at Scale', 'Join Jake Morrison as he reveals engineering techniques for achieving sub-second page loads and perfect Core Web Vitals.', 'spk-62', 'Main Stage', 1807134300000, 1807137000000, 'Technology', 'TALK', datetime('now')),
('ses-g28', 'conf-2025', 'Social Commerce Security: Protecting In-Platform Transactions', 'Join Jordan Taylor as he shares strategies for building secure, seamless shopping experiences within social media platforms.', 'spk-50', 'Hall A', 1807204500000, 1807207200000, 'Technology', 'TALK', datetime('now')),
('ses-g29', 'conf-2025', 'Circular Commerce: Building Platforms for Resale, Rental & Sustainability', 'Join Victoria Strand as she reveals how sustainable fashion technology enables circular commerce through resale and rental platforms.', 'spk-65', 'Room C', 1807217100000, 1807219800000, 'Customer Experience', 'TALK', datetime('now'));
